[project]
name = "mlops-actions"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "azure-ai-ml>=1.30.0",
    "azure-core>=1.36.0",
    "azure-identity>=1.25.1",
    "typer>=0.20.0",
]
